### ISSUE TITLE
"The request is blocked"

### ISSUE THREAD

**Issue by islandoflotuseaters** [Auction-Sniping/ShopGoodwillSniper#11]
Program won't load any pages, just keeps saying that, "The request is blocked". I'm guessing that Shopgoodwill is either blocking me specifically in the program and I'll need to clear cookies (how would I go about that with this program specifically?) or they're specifically blocking the method this program uses to interact with the site. This only stopped working a couple of days ago after working well for the last month, so a fix would be greatly appreciated.

**Comment by Auction-Sniping** [comment]
Please try updating to the latest version on http://SGWSniper.com

**Comment by islandoflotuseaters** [comment]
It's trying to make me pay for it again. I literally just purchased the lifetime subscription at the start of January...
