### ISSUE TITLE
After updating, program is trying to make me pay again

### ISSUE THREAD

**Issue by islandoflotuseaters** [auction-sniping/ShopGoodwillSniper#12]
Sorry, to open another issue,,however, I went and updated, but now it's trying to make me pay again for the program (at a higher cost as well), but I paid the "one time" payment fee only a month ago.

**Comment by Auction-Sniping** [comment]
Ok no problem don't worry I will supply you with a coupon code shortly...

**Comment by Auction-Sniping** [comment]
Ok can you please go ahead and purchase it one more time and then I will promptly cancel the payment?

**Comment by islandoflotuseaters** [comment]
Much appreciated. I just went to try and pay and it's throwing an error 

>Unhandled Error
Error: Could not call remote method 'setSize'. Check that the method signature is correct. Underlying error: TypeError: Error processing argument at index 0, conversion failure from Underlying stack: TypeError: Error processing argument at index 0, conversion failure from 
    at C:/Program Files/WindowsApps/21244AuctionSniper.Snipeable_24.2.416.0_x86__9qp5ttn8rz2vc/app/resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:480:71
    at IpcMainImpl.<anonymous> (C:/Program Files/WindowsApps/21244AuctionSniper.Snipeable_24.2.416.0_x86__9qp5ttn8rz2vc/app/resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:323:27)
    at IpcMainImpl.emit (node:events:513:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:89899)
    at WebContents.emit (node:events:513:28)
    at C:/Program Files/WindowsApps/21244AuctionSniper.Snipeable_24.2.416.0_x86__9qp5ttn8rz2vc/app/resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:483:25
    at IpcMainImpl.<anonymous> (C:/Program Files/WindowsApps/21244AuctionSniper.Snipeable_24.2.416.0_x86__9qp5ttn8rz2vc/app/resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:323:27)
    at IpcMainImpl.emit (node:events:513:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:89899)
    at WebContents.emit (node:events:513:28)

**Comment by islandoflotuseaters** [comment]
Just to clarify, it opens the license window, but when I click any of the "Buy" buttons it throws that error.

**Comment by Auction-Sniping** [comment]
Ok we are going to look into this today and get back to you shortly...

**Comment by islandoflotuseaters** [comment]
Thank you, I really appreciate it.

**Comment by Auction-Sniping** [comment]
Hi islandoflotuseaters,

We believe we have found the issue and it is a rare bug related to the size of your screen, furthermore, we have resolved the issue and posted an update, please update to the latest version on the Microsoft Windows App Store here:

https://apps.microsoft.com/detail/9NLHNKNJM66J

Once you have updated to the newest version above then try your payment again then let us know once that is completed so we can cancel your payment...

**Comment by islandoflotuseaters** [comment]
That fixed it, thank you. I just sent payment, once the payment is canceled I'll update here.

**Comment by Auction-Sniping** [comment]
Hi islandoflotuseaters,

Your payment has been cancelled now, it can take up to 7 days for it to show, please let us know if there is anything else we can assist you with!

**Comment by islandoflotuseaters** [comment]
I see it in the pending. Thank you, you all are awesome.

To anyone reading this: Program is great, works exactly as it is supposed to. You'll see some people say that they have missed bids, but if you ever snipe by hand (which I exclusively did before this), then you should know that occasional missed bids happen and they're mainly caused by how bad the site gets when it's under heavy stress and just refuses to load pages. On days with heavy strain, just set the timer higher. Also as you can see with this exchange, Auction-Sniping is trustworthy and still offers support even after they've received your purchase.

Thanks again.

**Comment by Auction-Sniping** [comment]
Thank you very much for your words of appreciation, if you don't mind can you please post them in a review on our App Store page below?

https://apps.microsoft.com/detail/9NLHNKNJM66J

**Comment by Auction-Sniping** [comment]
You can post your review below

ms-windows-store://pdp/?productid=9NLHNKNJM66J
