### ISSUE TITLE
When I try to download the zip it says Page not found.

### ISSUE THREAD

**Issue by zlip123** [Auction-Sniping/ShopGoodwillSniper#13]
I can't access the application. How much is the one-time fee?

**Comment by Auction-Sniping** [comment]
Hi Zelda,

Our prices start from $1 for 1 snipe all the way upto $249 one-time fee for unlimited life-time snipes, you can always download the latest version from the Microsoft Windows App Store here:

https://apps.microsoft.com/detail/9NLHNKNJM66J
